
study_accession: PRJEB6609 
input_ena_table: input/ENA-tables/PRJEB6609_PE.txt
outputDIR: /vortexfs1/omics/alexander/data/TARA 
scratch:  /vortexfs1/scratch/halexander
rerun-incomplete: True
keep-going: True
latency-wait: 10
max-jobs-per-second: 1
restart-times: 2
